### 异步解决方案之Promise  
---

#### 一. 问题情况 [SITUATION]  
javascript是一个单线程的世界。  
当我们需要同时做多件事情的时候，  
异步操作就能够帮助我们解决这个问题。  
比如说：axios正是基于Promise完成的。  
另外，推荐下面几个文章：  
参考廖雪峰大神的[[介绍Promise]](https://www.liaoxuefeng.com/wiki/1022910821149312/1023024413276544)  
简书上王云飞_小四_wyunfei的[[promise]](https://www.jianshu.com/p/1b63a13c2701)  
CSDN上傻小胖的[[ES6 Promise用法小结]](https://blog.csdn.net/qq_34645412/article/details/81170576)  
更能帮我们理解。  

#### 二. 任务目标 [TASK]  
Promise可以理解成是一个构造函数，  
有三种状态：  
* pending(进行中)  
* fulfilled(已成功)  
* rejected(已失败)  
自己身上有几个方法：  
* all(全部执行，汇总结果)  
* race(谁先完成，结果用谁)  
* resolve(pending => fulfilled)  
* reject(pending => rejected)  
在原型上有几个方法：  
* then(接受成功/失败的回调)  
* catch(捕获异常/失败的回调)  

#### 三. 代码实现 [ACTION]  
首先，我们做一个简单使用resolve、reject以及链式调用的小例子
``` javascript
function double(nNum) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const nResult = nNum * 2
      console.log("function double:", nResult)
      resolve(nResult)
    }, 1000)
  })
}

function floor(nNum) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const nResult = Math.floor(nNum)
      console.log("function floor:", nResult)
      resolve(nResult)
    }, 1000)
  })
}

function show(nNum) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (nNum > 10) {
        console.log("Resolve: function show:", nNum)
        resolve(nNum)
      } else {
        console.log("Reject: function show:", nNum)
        reject(nNum)
      }
    }, 1000)
  })
}

console.log("1st")
var p = new Promise((resolve, reject) => {
  const nNum = Math.random() * 10
  console.log("Program start. Number:", nNum)
  resolve(nNum)
})
console.log("2nd")
// then 的第二个参数 与 catch 是等价的
p.then(double)
.then(floor)
.then(show)
.then((nNum) => {
  console.log("Then: Resolve", nNum)
}, (nNum) => {
  console.log("Then: Reject", nNum)
})
.then(() => {
  // then 如果没有返回值，则直接运行
  console.log("3rd")
}).catch((nNum) => {
  console.error("Catch.", nNum)
})
console.log("4th")
```
运行结果示例：成功
``` bash
1st
Program start. Number: 8.37136065112828
2nd
4th
function double: 16.74272130225656
function floor: 16
Resolve: function show: 16
Then: Resolve 16
3rd
```
运行结果示例：失败
``` bash
1st
Program start. Number: 0.06554650667369044
2nd
4th
function double: 0.13109301334738088
function floor: 0
Reject: function show: 0
Then: Reject 0
3rd
```
  
其次，我们做一个应用 all 的小例子  
``` javascript
var p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("p1 Result")
  }, 3000)
})

var p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("p2 Result")
  }, 1000)
})

Promise.all([p1, p2]).then((result) => {
  console.log(result)
})
```
运行结果示例：  
``` bash
(2) ["p1 Result", "p2 Result"]
```
  
最后，我们做一个应用 race 的小例子  
``` javascript
var p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("p1 Result")
  }, 3000)
})

var p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("p2 Result")
  }, 1000)
})

Promise.race([p1, p2]).then((result) => {
  console.log(result)
})
```
运行结果示例：
``` bash
p2 Result
```  

新增，今天我在思否上看到一篇文章，  
如果手动实现的promise中，  
连续执行两次resolve，  
会怎么样？  
那么就用代码测试一下。  
``` javascript
var p1 = new Promise((resolve, reject) => {
  resolve("ResultAAAAA")
  resolve("ResultBBBBB")
})

p1.then((result) => {
  console.log('1', result)
}, (result) => {
  console.log('2', result)
})
```
那么，结果是：  
只会执行第一个resolve语句。  
``` bash
1 ResultAAAAA
```
#### 四. 结论总结 [RESULT]  
这篇文章写了好久，  
也是一直以来都没有太搞懂Promise的缘故。  
自己能够敲出来也是一个进步吧。  
另外，在看廖雪峰大神的代码的时候发现这么一句。  
``` javascript
setTimeout(resolve, 600, 'P2');
```
我当时懵掉，怎么会有第三个参数。  
Promise没搞懂，又出来个新问题。  
这就是回调地狱么[笑哭]  
赶紧查了查语法，  
发现一直最常用的定时器竟然是这么声明的：  
(IE9 及其更早版本不支持第三个参数)
``` javascript
setTimeout(function, milliseconds, param1, param2, ...)
```
看样子再熟悉的操作，  
里面都可能包含着自己的知识盲区。  
每天进步一点点，总会成功的。  